// mapConfig.js - Map layout and tile resource distribution
// REQ-CONFIG-001: Map configuration in separate config file
// Based on Appendix B: Map Layout Example

export const mapConfig = {
  // Grid dimensions
  width: 10,
  height: 10,

  // Starting position (center of map)
  startingTile: {
    q: 5,
    r: 3
  },

  // Tile resource layout (10×10 grid)
  // Row-by-row definition using offset coordinates
  // Types: 'iron', 'silicon', 'empty', 'start' (starting base)
  // Note: Energy is now generated by structures (solar panels) instead of tiles
  layout: [
    // Row 0
    ['empty', 'empty', 'iron', 'empty', 'empty', 'empty', 'empty', 'empty', 'silicon', 'empty'],
    // Row 1
    ['empty', 'iron', 'empty', 'empty', 'silicon', 'empty', 'empty', 'empty', 'empty', 'empty'],
    // Row 2
    ['iron', 'empty', 'empty', 'silicon', 'empty', 'empty', 'empty', 'iron', 'empty', 'empty'],
    // Row 3
    ['empty', 'empty', 'empty', 'empty', 'empty', 'start', 'empty', 'empty', 'silicon', 'empty'],
    // Row 4
    ['empty', 'silicon', 'empty', 'empty', 'iron', 'empty', 'iron', 'empty', 'empty', 'empty'],
    // Row 5
    ['empty', 'empty', 'empty', 'iron', 'empty', 'empty', 'empty', 'empty', 'empty', 'silicon'],
    // Row 6
    ['empty', 'empty', 'silicon', 'empty', 'empty', 'empty', 'empty', 'empty', 'iron', 'empty'],
    // Row 7
    ['empty', 'iron', 'empty', 'empty', 'silicon', 'empty', 'empty', 'empty', 'empty', 'empty'],
    // Row 8
    ['silicon', 'empty', 'empty', 'empty', 'empty', 'iron', 'empty', 'empty', 'empty', 'empty'],
    // Row 9
    ['empty', 'empty', 'empty', 'iron', 'empty', 'empty', 'silicon', 'empty', 'empty', 'empty']
  ]
};

// Resource counts (for reference):
// Iron: ~10 tiles
// Silicon: ~10 tiles
// Empty: ~79 tiles (energy tiles now empty, structures can be built here)
// Start: 1 tile
