// tiles.js - Tile type definitions and configuration
// REQ-CFG-002: Tile type configuration system

/**
 * Tile type definitions
 * Each tile type has:
 * - id: unique identifier
 * - name: display name (i18n key)
 * - resourceProduced: resource generated by drones on this tile
 * - baseRate: base production rate per drone
 * - allowedDrones: array of drone IDs that can work on this tile type
 */
export const TILE_TYPES = {
  iron: {
    id: 'iron',
    name: 'tiles.iron',
    resourceProduced: 'iron',
    baseRate: 1.0,
    allowedDrones: ['basicGatherer'] // Can be expanded with more drone types
  },
  
  silicon: {
    id: 'silicon',
    name: 'tiles.silicon',
    resourceProduced: 'silicon',
    baseRate: 1.0,
    allowedDrones: ['basicGatherer']
  },
  
  empty: {
    id: 'empty',
    name: 'tiles.empty',
    resourceProduced: null,
    baseRate: 0,
    allowedDrones: [] // No drones can work on empty tiles
  }
};

/**
 * Get tile type definition by ID
 * Checks localStorage for custom tile types in dev mode
 * @param {string} tileTypeId - Tile type identifier
 * @returns {object|null} Tile type definition or null if not found
 */
export function getTileType(tileTypeId) {
  // Check default tile types first
  if (TILE_TYPES[tileTypeId]) {
    return TILE_TYPES[tileTypeId];
  }
  
  // Check if it's a custom tile type
  if (tileTypeId.startsWith('custom_')) {
    const customTileTypes = localStorage.getItem('dev_tiles_override');
    if (customTileTypes) {
      try {
        const overrides = JSON.parse(customTileTypes);
        return overrides[tileTypeId] || null;
      } catch (error) {
        console.warn('Failed to load custom tile type:', error);
      }
    }
  }
  
  return null;
}

/**
 * Get all tile types including custom ones
 * @returns {object} All tile types (default + custom)
 */
export function getAllTileTypes() {
  const allTileTypes = { ...TILE_TYPES };
  
  // Add custom tile types from localStorage (dev mode)
  const customTileTypes = localStorage.getItem('dev_tiles_override');
  if (customTileTypes) {
    try {
      const overrides = JSON.parse(customTileTypes);
      Object.assign(allTileTypes, overrides);
    } catch (error) {
      console.warn('Failed to load custom tile types:', error);
    }
  }
  
  return allTileTypes;
}

/**
 * Get list of all tile type IDs
 * @returns {string[]} Array of tile type IDs
 */
export function getAllTileTypeIds() {
  return Object.keys(getAllTileTypes());
}
